#!/usr/bin/env bash
#Bash script that creates an RSA key pair.
mkdir -p /Users/Shema/Documents/projects/ALU-WORK/alu-system_engineering-devops/ssh
ssh-keygen -t rsa -b 4096 -f /Users/Shema/Documents/projects/ALU-WORK/alu-system_engineering-devops/ssh/school -N "betty" 
