#!/bin/bash

apt-get update
apt-get install -y nginx

sed -i 's/^\(\s*listen\s*.*:\)\(.*\)/\180;\2/' /etc/nginx/sites-available/default

# Start Nginx
service nginx start

# Check HTML document using curl
curl -s 0:80

# Stop Nginx
service nginx stop

# Check Nginx status
service nginx status || true
