#!/usr/bin/env bash

# Install nginx with -y option
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
/etc/init.d/nginx restart

echo "Holberton School for the win!" > /usr/share/nginx/html/index.html

ps aux | grep nginx | grep -v grep > /dev/null

if [ $? -eq 0 ]; then
    echo "Nginx installed and configured successfully."
else
    echo "Installation or configuration failed. Check nginx logs for more details."
fi
