#!/usr/bin/env bash

# Update package lists and upgrade
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to serve content at root /
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        echo "Holberton School for the win!";
    }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
