#!/usr/bin/env bash
#Install nginx
sudo apt update
sudo apt install nginx -y

#config for redirect
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configurations if needed
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t

#Restart nginx
sudo service nginx restart
