#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx for custom 404 page
config_file="/etc/nginx/sites-available/default"
custom_404_config="\
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}"

# Replace the existing server block with the new configuration
echo "$custom_404_config" | sudo tee "$config_file" > /dev/null

# Reload Nginx to apply the changes
sudo service nginx reload
